# Generated by Django 2.2.9 on 2020-06-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testproducts', '0002_product_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
    ]
