# Generated by Django 2.2.5 on 2020-06-18 09:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('shipping', '0003_auto_20190322_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='collection',
            field=models.ForeignKey(default=wagtail.core.models.get_root_collection_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Collection', verbose_name='collection'),
        ),
    ]
